#!/bin/sh
# postinst script for libaasdk

set -e

case "$1" in
    configure)
        # Update the dynamic linker cache
        if [ -x /sbin/ldconfig ]; then
            /sbin/ldconfig
        fi
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
