#!/bin/sh
# prerm script for libaasdk

set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Nothing specific to do
        ;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
